<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Mahasiswa extends CI_Controller{
    function __construct(){
        parent::__construct();
        $this->load->model('Mahasiswa_model');
    } 

    function index(){
        $data['mahasiswa'] = $this->Mahasiswa_model->show_mahasiswa();
        $data['judul'] = "Tabel Mahasiswa";
        $data['konten'] = "List Mahasiswa";
        $data['_view'] = 'page/mahasiswa/index';
        $this->load->view('layouts/main', $data);
    }

    /*
     * Adding a new mahasiswa
     */
    function add(){   
        $data['list'] = $this->Mahasiswa_model->show_mahasiswa();
        if(isset($_POST) && count($_POST) > 0){   
            $store = array(
				'NIM' => $this->input->post('NIM'),
				'mhs_nama' => $this->input->post('mhs_nama'),
				'mhs_tpt_lhr' => $this->input->post('mhs_tpt_lhr'),
				'mhs_tgl_lhr' => $this->input->post('mhs_tgl_lhr'),
				'mhs_jurusan' => $this->input->post('mhs_jurusan'),
				'mhs_ipk' => $this->input->post('mhs_ipk'),
            );
            
            $mahasiswa_id = $this->Mahasiswa_model->add_mahasiswa($store);
            redirect('mahasiswa/index');
        }
        else {
            $data['_view'] = 'page/mahasiswa/add';
            $data['judul'] = "Tambah Mahasiswa";
            $data['konten'] = "Tambah Mahasiswa";
            $this->load->view('layouts/main', $data);
        }
    }  

    function edit($NIM) {   
        $data['mahasiswa'] = $this->Mahasiswa_model->get_mahasiswa($NIM);//cari data
        $data['list'] = $this->Mahasiswa_model->show_mahasiswa();
        if(isset($data['mahasiswa']['NIM'])){
            if(isset($_POST) && count($_POST) > 0) {   
                $update = array(
                    'NIM' => $this->input->post('NIM'),
					'mhs_nama' => $this->input->post('mhs_nama'),
					'mhs_tpt_lhr' => $this->input->post('mhs_tpt_lhr'),
					'mhs_tgl_lhr' => $this->input->post('mhs_tgl_lhr'),
					'mhs_jurusan' => $this->input->post('mhs_jurusan'),
					'mhs_ipk' => $this->input->post('mhs_ipk'),
                );

                $this->Mahasiswa_model->update_mahasiswa($NIM,$update);            
                redirect('mahasiswa/index');
            }
            else{
                $data['_view'] = 'page/mahasiswa/edit';
                $data['judul'] = "Edit Mahasiswa";
                $data['konten'] = "Edit Mahasiswa";
                $this->load->view('layouts/main', $data);
            }
        }
        else {
            $data['code'] = '404';
            $data['ket'] = "Edit Mahasiswa gagal. ya iyalah datanya gak ada -_-";
            $data['back'] = "mahasiswa/";
            $this->load->view('page/eror',$data);
        }
    } 

    function delete($NIM){
        $mahasiswa = $this->Mahasiswa_model->get_mahasiswa($NIM);
        
        if(isset($mahasiswa['NIM'])){
            $this->Mahasiswa_model->delete_mahasiswa($NIM);
            redirect('mahasiswa/index');
        }
        else {
            $data['code'] = '404';
            $data['ket'] = "Edit Mahasiswa gagal. ya iyalah datanya gak ada -_-";
            $data['back'] = "mahasiswa/";
            $this->load->view('page/eror',$data);
        }
    }

}
